controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    watcher_controller:
      type: diff_drive_controller/DiffDriveController

watcher_controller:
  ros__parameters:
    use_stamped_vel: true
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    publish_rate: 100.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    wheel_radius: 0.15875
    wheel_separation: 0.4953
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.5
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
     x:
       has_velocity_limits: true
       max_velocity: 2.0
       min_velocity: 0.0
       has_acceleration_limits: true
       max_acceleration: 0.5
       min_acceleration: 0.0
       has_jerk_limits: false

    angular:
      z:
       has_velocity_limits: true
       max_velocity: 1.5
       min_velocity: 0.0
       has_acceleration_limits: true
       max_acceleration: 0.5
       min_acceleration: 0.0
       has_jerk_limits: false
